// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "github.com/Arubacloud/arubacloud-resource-operator/internal/client"
	mock "github.com/stretchr/testify/mock"
)

// MockITokenManager is an autogenerated mock type for the ITokenManager type
type MockITokenManager struct {
	mock.Mock
}

type MockITokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITokenManager) EXPECT() *MockITokenManager_Expecter {
	return &MockITokenManager_Expecter{mock: &_m.Mock}
}

// GetAccessToken provides a mock function with given fields: checkCache, tenant
func (_m *MockITokenManager) GetAccessToken(checkCache bool, tenant string) (string, error) {
	ret := _m.Called(checkCache, tenant)

	if len(ret) == 0 {
		panic("no return value specified for GetAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(bool, string) (string, error)); ok {
		return rf(checkCache, tenant)
	}
	if rf, ok := ret.Get(0).(func(bool, string) string); ok {
		r0 = rf(checkCache, tenant)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(bool, string) error); ok {
		r1 = rf(checkCache, tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITokenManager_GetAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessToken'
type MockITokenManager_GetAccessToken_Call struct {
	*mock.Call
}

// GetAccessToken is a helper method to define mock.On call
//   - checkCache bool
//   - tenant string
func (_e *MockITokenManager_Expecter) GetAccessToken(checkCache interface{}, tenant interface{}) *MockITokenManager_GetAccessToken_Call {
	return &MockITokenManager_GetAccessToken_Call{Call: _e.mock.On("GetAccessToken", checkCache, tenant)}
}

func (_c *MockITokenManager_GetAccessToken_Call) Run(run func(checkCache bool, tenant string)) *MockITokenManager_GetAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool), args[1].(string))
	})
	return _c
}

func (_c *MockITokenManager_GetAccessToken_Call) Return(_a0 string, _a1 error) *MockITokenManager_GetAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITokenManager_GetAccessToken_Call) RunAndReturn(run func(bool, string) (string, error)) *MockITokenManager_GetAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveToken provides a mock function with given fields: tenant
func (_m *MockITokenManager) GetActiveToken(tenant string) string {
	ret := _m.Called(tenant)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tenant)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockITokenManager_GetActiveToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveToken'
type MockITokenManager_GetActiveToken_Call struct {
	*mock.Call
}

// GetActiveToken is a helper method to define mock.On call
//   - tenant string
func (_e *MockITokenManager_Expecter) GetActiveToken(tenant interface{}) *MockITokenManager_GetActiveToken_Call {
	return &MockITokenManager_GetActiveToken_Call{Call: _e.mock.On("GetActiveToken", tenant)}
}

func (_c *MockITokenManager_GetActiveToken_Call) Run(run func(tenant string)) *MockITokenManager_GetActiveToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockITokenManager_GetActiveToken_Call) Return(_a0 string) *MockITokenManager_GetActiveToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITokenManager_GetActiveToken_Call) RunAndReturn(run func(string) string) *MockITokenManager_GetActiveToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsExpiredHelper provides a mock function with given fields: cToken
func (_m *MockITokenManager) IsExpiredHelper(cToken *client.CachedToken) bool {
	ret := _m.Called(cToken)

	if len(ret) == 0 {
		panic("no return value specified for IsExpiredHelper")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*client.CachedToken) bool); ok {
		r0 = rf(cToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockITokenManager_IsExpiredHelper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExpiredHelper'
type MockITokenManager_IsExpiredHelper_Call struct {
	*mock.Call
}

// IsExpiredHelper is a helper method to define mock.On call
//   - cToken *client.CachedToken
func (_e *MockITokenManager_Expecter) IsExpiredHelper(cToken interface{}) *MockITokenManager_IsExpiredHelper_Call {
	return &MockITokenManager_IsExpiredHelper_Call{Call: _e.mock.On("IsExpiredHelper", cToken)}
}

func (_c *MockITokenManager_IsExpiredHelper_Call) Run(run func(cToken *client.CachedToken)) *MockITokenManager_IsExpiredHelper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*client.CachedToken))
	})
	return _c
}

func (_c *MockITokenManager_IsExpiredHelper_Call) Return(_a0 bool) *MockITokenManager_IsExpiredHelper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITokenManager_IsExpiredHelper_Call) RunAndReturn(run func(*client.CachedToken) bool) *MockITokenManager_IsExpiredHelper_Call {
	_c.Call.Return(run)
	return _c
}

// SetClientIdAndSecret provides a mock function with given fields: clientID, clientSecret
func (_m *MockITokenManager) SetClientIdAndSecret(clientID string, clientSecret string) {
	_m.Called(clientID, clientSecret)
}

// MockITokenManager_SetClientIdAndSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClientIdAndSecret'
type MockITokenManager_SetClientIdAndSecret_Call struct {
	*mock.Call
}

// SetClientIdAndSecret is a helper method to define mock.On call
//   - clientID string
//   - clientSecret string
func (_e *MockITokenManager_Expecter) SetClientIdAndSecret(clientID interface{}, clientSecret interface{}) *MockITokenManager_SetClientIdAndSecret_Call {
	return &MockITokenManager_SetClientIdAndSecret_Call{Call: _e.mock.On("SetClientIdAndSecret", clientID, clientSecret)}
}

func (_c *MockITokenManager_SetClientIdAndSecret_Call) Run(run func(clientID string, clientSecret string)) *MockITokenManager_SetClientIdAndSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockITokenManager_SetClientIdAndSecret_Call) Return() *MockITokenManager_SetClientIdAndSecret_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockITokenManager_SetClientIdAndSecret_Call) RunAndReturn(run func(string, string)) *MockITokenManager_SetClientIdAndSecret_Call {
	_c.Run(run)
	return _c
}

// NewMockITokenManager creates a new instance of MockITokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITokenManager {
	mock := &MockITokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
