run:
  timeout: 5m
  tests: true

version: '2'

linters:
  default: all
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec

formatters:
  enable:
    - gofmt

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
